on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ${{github.workspace}}
