on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip files
        run: cd ${{ github.workspace }} && zip -r MarvalSoftware.Plugins.Teams.zip .
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.sha }}
          prerelease: false
          title: Release ${{ github.sha }}
          files: ${{ github.workspace }}/MarvalSoftware.Plugins.Teams.zip
