on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Zip files
        run: cd ${{ github.workspace }} && zip -r Teams.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ${{ github.workspace }}/Teams.zip
