on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls
      - name: Zip files
        run: zip -r Teams.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: Teams.zip
